version: '3.8'

services:
  app:
    image: dauthang811/social-ai-task-service:latest
    environment:
      NODE_ENV: ${ENV}
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    configs:
      - source: social-ai-task-service-dev
        target: /app/.env
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

configs:
  social-ai-task-service:
    external: true

networks:
  app-net:
    external: true
